minor improvements to the file listing
qiita-spots/qtp-job-output-folder pull request #3
Opened 2021-09-07 18:07 UTC by antgonza

2021-09-08 18:09 UTC, ElDeveloper commented on qtp_job_output_folder/summary.py
> +    index_fp = join(out_dir, f"summary.html")
```suggestion
    index_fp = join(out_dir, "summary.html")
```

2021-10-25 15:15 UTC, antgonza commented
This is ready for review. One single reviewer is fine for merging. Note that these are the changes we are already using in qiita-rc.

2021-10-25 17:00 UTC, charles-cowart requested changes
Everything looks good. Requesting clarification on pip versioning before approving.

2021-10-25 17:00 UTC, charles-cowart commented on .github/workflows/qiita-plugin-ci.yml
> +          conda create -q --yes -n qiita python=3.6 pip==9.0.3 libgfortran numpy nginx cython redis
Pip is currently on version 21. Is there a reason for using pip 9 specifically? Especially since it
's upgraded in line 67

2021-10-25 17:19 UTC, antgonza commented on .github/workflows/qiita-plugin-ci.yml
> +          conda create -q --yes -n qiita python=3.6 pip==9.0.3 libgfortran numpy nginx cython redis
yes, conda with python 3.6 + a newer pip breaks, the solution is to ask for an older pip and install a new version via pip (if needed).

2021-10-26 04:12 UTC, charles-cowart commented on .github/workflows/qiita-plugin-ci.yml
> +          conda create -q --yes -n qiita python=3.6 pip==9.0.3 libgfortran numpy nginx cython redis
@antgonza this shouldn't be a show-stopper. I'll merge this in and I'll ask some other time.

2021-10-26 04:13 UTC, merged